### ISSUE TITLE
include file name add a prefix

### ISSUE THREAD

**Issue by skyformat99** [romuloceccon/lightmqtt#5]
As a small suggestion,  include file name add a prefix:
as:  lmqtt_client.h  ,lmqtt_time.h   etc.

Special files  "time.h   types.h" can easily conflict with system files "time.h   types.h " when compile.

thanks.

**Comment by romuloceccon** [comment]
You're supposed to add the parent of the directory containing those include files to the include path, so that in your application you'd do:

```c
#include <lightmqtt/types.h>
#include <lightmqtt/time.h>
/* ... */
```

That should be enough to avoid any conflicts.

**Comment by skyformat99** [comment]
Thank you for your reply. You're right. This method is ok.
However, if you add prefixes, you may be more consistent with the general solution.

**Comment by romuloceccon** [comment]
I believe that's a matter of taste. [libevent](http://libevent.org/) provides the header `event2/thread.h`, and [curl](https://github.com/curl/curl) provides `curl/system.h`, for example.

**Comment by skyformat99** [comment]
agree,  It's only a matter of taste. 
close it.
